import minecraft_launcher_lib
from uuid import uuid1
import subprocess
# -*- coding: utf-8 -*-
import minecraft_launcher_lib.utils
# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(502, 660)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(4, 110, 501, 51))
        self.label.setText("Boxmine")
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(0, 510, 501, 41))
        self.comboBox.setObjectName("comboBox")

        for version in minecraft_launcher_lib.utils.get_version_list():
            self.comboBox.addItem(version['id'])

        MainWindow.setCentralWidget(self.centralwidget)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 450, 501, 41))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setPlaceholderText("Username")
        self.lineEdit_2.setCursorPosition(0)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.start_game = QtWidgets.QPushButton(self.centralwidget)
        self.start_game.setGeometry(QtCore.QRect(0, 570, 501, 41))
        self.start_game.setText("Start")
        self.start_game.clicked.connect(self.launch_game)
        self.start_game.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

    def launch_game(self):
            version = self.comboBox.currentText()
            minecraft_launcher_lib.install.install_minecraft_version(versionid=version, minecraft_directory=('.minecraft'))

            username = self.lineEdit_2.text()
            if username == '':
                username = 'ghsdgpiuhdsuishrug5534534'

            options = {
                'username':'',
                'uuid': str(uuid1()),
                'token': ''
            }

            subprocess.call(minecraft_launcher_lib.command.get_minecraft_command(version=version, minecraft_directory=('.minecraft'), options=options))

            QtCore.QMetaObject.connectSlotsByName(MainWindow)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
